//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace ListaSerwisow.ArcGIS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.1", ConfigurationName="ArcGIS.ServiceCatalogPort")]
    public interface ServiceCatalogPort {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetMessageVersion(ListaSerwisow.ArcGIS.GetMessageVersionRequest request, System.AsyncCallback callback, object asyncState);
        
        ListaSerwisow.ArcGIS.GetMessageVersionResponse EndGetMessageVersion(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetMessageFormats(ListaSerwisow.ArcGIS.GetMessageFormatsRequest request, System.AsyncCallback callback, object asyncState);
        
        ListaSerwisow.ArcGIS.GetMessageFormatsResponse EndGetMessageFormats(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetTokenServiceURL(ListaSerwisow.ArcGIS.GetTokenServiceURLRequest request, System.AsyncCallback callback, object asyncState);
        
        ListaSerwisow.ArcGIS.GetTokenServiceURLResponse EndGetTokenServiceURL(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetFolders(ListaSerwisow.ArcGIS.GetFoldersRequest request, System.AsyncCallback callback, object asyncState);
        
        ListaSerwisow.ArcGIS.GetFoldersResponse EndGetFolders(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetServiceDescriptions(ListaSerwisow.ArcGIS.GetServiceDescriptionsRequest request, System.AsyncCallback callback, object asyncState);
        
        ListaSerwisow.ArcGIS.GetServiceDescriptionsResponse EndGetServiceDescriptions(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginRequiresTokens(ListaSerwisow.ArcGIS.RequiresTokensRequest request, System.AsyncCallback callback, object asyncState);
        
        ListaSerwisow.ArcGIS.RequiresTokensResponse EndRequiresTokens(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetServiceDescriptionsEx(ListaSerwisow.ArcGIS.GetServiceDescriptionsExRequest request, System.AsyncCallback callback, object asyncState);
        
        ListaSerwisow.ArcGIS.GetServiceDescriptionsExResponse EndGetServiceDescriptionsEx(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.1")]
    public enum esriArcGISVersion {
        
        /// <remarks/>
        esriArcGISVersion83,
        
        /// <remarks/>
        esriArcGISVersion90,
        
        /// <remarks/>
        esriArcGISVersion92,
        
        /// <remarks/>
        esriArcGISVersion93,
        
        /// <remarks/>
        esriArcGISVersion10,
        
        /// <remarks/>
        esriArcGISVersion101,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageVersion", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.1", IsWrapped=true)]
    public partial class GetMessageVersionRequest {
        
        public GetMessageVersionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageVersionResponse", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.1", IsWrapped=true)]
    public partial class GetMessageVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ListaSerwisow.ArcGIS.esriArcGISVersion MessageVersion;
        
        public GetMessageVersionResponse() {
        }
        
        public GetMessageVersionResponse(ListaSerwisow.ArcGIS.esriArcGISVersion MessageVersion) {
            this.MessageVersion = MessageVersion;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.1")]
    public enum esriServiceCatalogMessageFormat {
        
        /// <remarks/>
        esriServiceCatalogMessageFormatSoap,
        
        /// <remarks/>
        esriServiceCatalogMessageFormatBin,
        
        /// <remarks/>
        esriServiceCatalogMessageFormatSoapOrBin,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageFormats", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.1", IsWrapped=true)]
    public partial class GetMessageFormatsRequest {
        
        public GetMessageFormatsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageFormatsResponse", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.1", IsWrapped=true)]
    public partial class GetMessageFormatsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ListaSerwisow.ArcGIS.esriServiceCatalogMessageFormat MessageFormats;
        
        public GetMessageFormatsResponse() {
        }
        
        public GetMessageFormatsResponse(ListaSerwisow.ArcGIS.esriServiceCatalogMessageFormat MessageFormats) {
            this.MessageFormats = MessageFormats;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTokenServiceURL", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.1", IsWrapped=true)]
    public partial class GetTokenServiceURLRequest {
        
        public GetTokenServiceURLRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTokenServiceURLResponse", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.1", IsWrapped=true)]
    public partial class GetTokenServiceURLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TokenServiceURL;
        
        public GetTokenServiceURLResponse() {
        }
        
        public GetTokenServiceURLResponse(string TokenServiceURL) {
            this.TokenServiceURL = TokenServiceURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFolders", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.1", IsWrapped=true)]
    public partial class GetFoldersRequest {
        
        public GetFoldersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFoldersResponse", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.1", IsWrapped=true)]
    public partial class GetFoldersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.1", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("String", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] FolderNames;
        
        public GetFoldersResponse() {
        }
        
        public GetFoldersResponse(string[] FolderNames) {
            this.FolderNames = FolderNames;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18047")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.1")]
    public partial class ServiceDescription : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string typeField;
        
        private string urlField;
        
        private string parentTypeField;
        
        private string capabilitiesField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("Url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ParentType {
            get {
                return this.parentTypeField;
            }
            set {
                this.parentTypeField = value;
                this.RaisePropertyChanged("ParentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Capabilities {
            get {
                return this.capabilitiesField;
            }
            set {
                this.capabilitiesField = value;
                this.RaisePropertyChanged("Capabilities");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceDescriptions", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.1", IsWrapped=true)]
    public partial class GetServiceDescriptionsRequest {
        
        public GetServiceDescriptionsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceDescriptionsResponse", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.1", IsWrapped=true)]
    public partial class GetServiceDescriptionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.1", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ListaSerwisow.ArcGIS.ServiceDescription[] ServiceDescriptions;
        
        public GetServiceDescriptionsResponse() {
        }
        
        public GetServiceDescriptionsResponse(ListaSerwisow.ArcGIS.ServiceDescription[] ServiceDescriptions) {
            this.ServiceDescriptions = ServiceDescriptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequiresTokens", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.1", IsWrapped=true)]
    public partial class RequiresTokensRequest {
        
        public RequiresTokensRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequiresTokensResponse", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.1", IsWrapped=true)]
    public partial class RequiresTokensResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Result;
        
        public RequiresTokensResponse() {
        }
        
        public RequiresTokensResponse(bool Result) {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceDescriptionsEx", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.1", IsWrapped=true)]
    public partial class GetServiceDescriptionsExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FolderName;
        
        public GetServiceDescriptionsExRequest() {
        }
        
        public GetServiceDescriptionsExRequest(string FolderName) {
            this.FolderName = FolderName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceDescriptionsExResponse", WrapperNamespace="http://www.esri.com/schemas/ArcGIS/10.1", IsWrapped=true)]
    public partial class GetServiceDescriptionsExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.esri.com/schemas/ArcGIS/10.1", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ListaSerwisow.ArcGIS.ServiceDescription[] ServiceDescriptions;
        
        public GetServiceDescriptionsExResponse() {
        }
        
        public GetServiceDescriptionsExResponse(ListaSerwisow.ArcGIS.ServiceDescription[] ServiceDescriptions) {
            this.ServiceDescriptions = ServiceDescriptions;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceCatalogPortChannel : ListaSerwisow.ArcGIS.ServiceCatalogPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMessageVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMessageVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ListaSerwisow.ArcGIS.esriArcGISVersion Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ListaSerwisow.ArcGIS.esriArcGISVersion)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMessageFormatsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMessageFormatsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ListaSerwisow.ArcGIS.esriServiceCatalogMessageFormat Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ListaSerwisow.ArcGIS.esriServiceCatalogMessageFormat)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTokenServiceURLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTokenServiceURLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFoldersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFoldersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetServiceDescriptionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetServiceDescriptionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ListaSerwisow.ArcGIS.ServiceDescription[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ListaSerwisow.ArcGIS.ServiceDescription[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequiresTokensCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RequiresTokensCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetServiceDescriptionsExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetServiceDescriptionsExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ListaSerwisow.ArcGIS.ServiceDescription[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ListaSerwisow.ArcGIS.ServiceDescription[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCatalogPortClient : System.ServiceModel.ClientBase<ListaSerwisow.ArcGIS.ServiceCatalogPort>, ListaSerwisow.ArcGIS.ServiceCatalogPort {
        
        private BeginOperationDelegate onBeginGetMessageVersionDelegate;
        
        private EndOperationDelegate onEndGetMessageVersionDelegate;
        
        private System.Threading.SendOrPostCallback onGetMessageVersionCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMessageFormatsDelegate;
        
        private EndOperationDelegate onEndGetMessageFormatsDelegate;
        
        private System.Threading.SendOrPostCallback onGetMessageFormatsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTokenServiceURLDelegate;
        
        private EndOperationDelegate onEndGetTokenServiceURLDelegate;
        
        private System.Threading.SendOrPostCallback onGetTokenServiceURLCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFoldersDelegate;
        
        private EndOperationDelegate onEndGetFoldersDelegate;
        
        private System.Threading.SendOrPostCallback onGetFoldersCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetServiceDescriptionsDelegate;
        
        private EndOperationDelegate onEndGetServiceDescriptionsDelegate;
        
        private System.Threading.SendOrPostCallback onGetServiceDescriptionsCompletedDelegate;
        
        private BeginOperationDelegate onBeginRequiresTokensDelegate;
        
        private EndOperationDelegate onEndRequiresTokensDelegate;
        
        private System.Threading.SendOrPostCallback onRequiresTokensCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetServiceDescriptionsExDelegate;
        
        private EndOperationDelegate onEndGetServiceDescriptionsExDelegate;
        
        private System.Threading.SendOrPostCallback onGetServiceDescriptionsExCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ServiceCatalogPortClient() {
        }
        
        public ServiceCatalogPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCatalogPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCatalogPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCatalogPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetMessageVersionCompletedEventArgs> GetMessageVersionCompleted;
        
        public event System.EventHandler<GetMessageFormatsCompletedEventArgs> GetMessageFormatsCompleted;
        
        public event System.EventHandler<GetTokenServiceURLCompletedEventArgs> GetTokenServiceURLCompleted;
        
        public event System.EventHandler<GetFoldersCompletedEventArgs> GetFoldersCompleted;
        
        public event System.EventHandler<GetServiceDescriptionsCompletedEventArgs> GetServiceDescriptionsCompleted;
        
        public event System.EventHandler<RequiresTokensCompletedEventArgs> RequiresTokensCompleted;
        
        public event System.EventHandler<GetServiceDescriptionsExCompletedEventArgs> GetServiceDescriptionsExCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ListaSerwisow.ArcGIS.ServiceCatalogPort.BeginGetMessageVersion(ListaSerwisow.ArcGIS.GetMessageVersionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMessageVersion(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetMessageVersion(System.AsyncCallback callback, object asyncState) {
            ListaSerwisow.ArcGIS.GetMessageVersionRequest inValue = new ListaSerwisow.ArcGIS.GetMessageVersionRequest();
            return ((ListaSerwisow.ArcGIS.ServiceCatalogPort)(this)).BeginGetMessageVersion(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ListaSerwisow.ArcGIS.GetMessageVersionResponse ListaSerwisow.ArcGIS.ServiceCatalogPort.EndGetMessageVersion(System.IAsyncResult result) {
            return base.Channel.EndGetMessageVersion(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private ListaSerwisow.ArcGIS.esriArcGISVersion EndGetMessageVersion(System.IAsyncResult result) {
            ListaSerwisow.ArcGIS.GetMessageVersionResponse retVal = ((ListaSerwisow.ArcGIS.ServiceCatalogPort)(this)).EndGetMessageVersion(result);
            return retVal.MessageVersion;
        }
        
        private System.IAsyncResult OnBeginGetMessageVersion(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetMessageVersion(callback, asyncState);
        }
        
        private object[] OnEndGetMessageVersion(System.IAsyncResult result) {
            ListaSerwisow.ArcGIS.esriArcGISVersion retVal = this.EndGetMessageVersion(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMessageVersionCompleted(object state) {
            if ((this.GetMessageVersionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMessageVersionCompleted(this, new GetMessageVersionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMessageVersionAsync() {
            this.GetMessageVersionAsync(null);
        }
        
        public void GetMessageVersionAsync(object userState) {
            if ((this.onBeginGetMessageVersionDelegate == null)) {
                this.onBeginGetMessageVersionDelegate = new BeginOperationDelegate(this.OnBeginGetMessageVersion);
            }
            if ((this.onEndGetMessageVersionDelegate == null)) {
                this.onEndGetMessageVersionDelegate = new EndOperationDelegate(this.OnEndGetMessageVersion);
            }
            if ((this.onGetMessageVersionCompletedDelegate == null)) {
                this.onGetMessageVersionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMessageVersionCompleted);
            }
            base.InvokeAsync(this.onBeginGetMessageVersionDelegate, null, this.onEndGetMessageVersionDelegate, this.onGetMessageVersionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ListaSerwisow.ArcGIS.ServiceCatalogPort.BeginGetMessageFormats(ListaSerwisow.ArcGIS.GetMessageFormatsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMessageFormats(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetMessageFormats(System.AsyncCallback callback, object asyncState) {
            ListaSerwisow.ArcGIS.GetMessageFormatsRequest inValue = new ListaSerwisow.ArcGIS.GetMessageFormatsRequest();
            return ((ListaSerwisow.ArcGIS.ServiceCatalogPort)(this)).BeginGetMessageFormats(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ListaSerwisow.ArcGIS.GetMessageFormatsResponse ListaSerwisow.ArcGIS.ServiceCatalogPort.EndGetMessageFormats(System.IAsyncResult result) {
            return base.Channel.EndGetMessageFormats(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private ListaSerwisow.ArcGIS.esriServiceCatalogMessageFormat EndGetMessageFormats(System.IAsyncResult result) {
            ListaSerwisow.ArcGIS.GetMessageFormatsResponse retVal = ((ListaSerwisow.ArcGIS.ServiceCatalogPort)(this)).EndGetMessageFormats(result);
            return retVal.MessageFormats;
        }
        
        private System.IAsyncResult OnBeginGetMessageFormats(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetMessageFormats(callback, asyncState);
        }
        
        private object[] OnEndGetMessageFormats(System.IAsyncResult result) {
            ListaSerwisow.ArcGIS.esriServiceCatalogMessageFormat retVal = this.EndGetMessageFormats(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMessageFormatsCompleted(object state) {
            if ((this.GetMessageFormatsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMessageFormatsCompleted(this, new GetMessageFormatsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMessageFormatsAsync() {
            this.GetMessageFormatsAsync(null);
        }
        
        public void GetMessageFormatsAsync(object userState) {
            if ((this.onBeginGetMessageFormatsDelegate == null)) {
                this.onBeginGetMessageFormatsDelegate = new BeginOperationDelegate(this.OnBeginGetMessageFormats);
            }
            if ((this.onEndGetMessageFormatsDelegate == null)) {
                this.onEndGetMessageFormatsDelegate = new EndOperationDelegate(this.OnEndGetMessageFormats);
            }
            if ((this.onGetMessageFormatsCompletedDelegate == null)) {
                this.onGetMessageFormatsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMessageFormatsCompleted);
            }
            base.InvokeAsync(this.onBeginGetMessageFormatsDelegate, null, this.onEndGetMessageFormatsDelegate, this.onGetMessageFormatsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ListaSerwisow.ArcGIS.ServiceCatalogPort.BeginGetTokenServiceURL(ListaSerwisow.ArcGIS.GetTokenServiceURLRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTokenServiceURL(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetTokenServiceURL(System.AsyncCallback callback, object asyncState) {
            ListaSerwisow.ArcGIS.GetTokenServiceURLRequest inValue = new ListaSerwisow.ArcGIS.GetTokenServiceURLRequest();
            return ((ListaSerwisow.ArcGIS.ServiceCatalogPort)(this)).BeginGetTokenServiceURL(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ListaSerwisow.ArcGIS.GetTokenServiceURLResponse ListaSerwisow.ArcGIS.ServiceCatalogPort.EndGetTokenServiceURL(System.IAsyncResult result) {
            return base.Channel.EndGetTokenServiceURL(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetTokenServiceURL(System.IAsyncResult result) {
            ListaSerwisow.ArcGIS.GetTokenServiceURLResponse retVal = ((ListaSerwisow.ArcGIS.ServiceCatalogPort)(this)).EndGetTokenServiceURL(result);
            return retVal.TokenServiceURL;
        }
        
        private System.IAsyncResult OnBeginGetTokenServiceURL(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetTokenServiceURL(callback, asyncState);
        }
        
        private object[] OnEndGetTokenServiceURL(System.IAsyncResult result) {
            string retVal = this.EndGetTokenServiceURL(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTokenServiceURLCompleted(object state) {
            if ((this.GetTokenServiceURLCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTokenServiceURLCompleted(this, new GetTokenServiceURLCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTokenServiceURLAsync() {
            this.GetTokenServiceURLAsync(null);
        }
        
        public void GetTokenServiceURLAsync(object userState) {
            if ((this.onBeginGetTokenServiceURLDelegate == null)) {
                this.onBeginGetTokenServiceURLDelegate = new BeginOperationDelegate(this.OnBeginGetTokenServiceURL);
            }
            if ((this.onEndGetTokenServiceURLDelegate == null)) {
                this.onEndGetTokenServiceURLDelegate = new EndOperationDelegate(this.OnEndGetTokenServiceURL);
            }
            if ((this.onGetTokenServiceURLCompletedDelegate == null)) {
                this.onGetTokenServiceURLCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTokenServiceURLCompleted);
            }
            base.InvokeAsync(this.onBeginGetTokenServiceURLDelegate, null, this.onEndGetTokenServiceURLDelegate, this.onGetTokenServiceURLCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ListaSerwisow.ArcGIS.ServiceCatalogPort.BeginGetFolders(ListaSerwisow.ArcGIS.GetFoldersRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFolders(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetFolders(System.AsyncCallback callback, object asyncState) {
            ListaSerwisow.ArcGIS.GetFoldersRequest inValue = new ListaSerwisow.ArcGIS.GetFoldersRequest();
            return ((ListaSerwisow.ArcGIS.ServiceCatalogPort)(this)).BeginGetFolders(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ListaSerwisow.ArcGIS.GetFoldersResponse ListaSerwisow.ArcGIS.ServiceCatalogPort.EndGetFolders(System.IAsyncResult result) {
            return base.Channel.EndGetFolders(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string[] EndGetFolders(System.IAsyncResult result) {
            ListaSerwisow.ArcGIS.GetFoldersResponse retVal = ((ListaSerwisow.ArcGIS.ServiceCatalogPort)(this)).EndGetFolders(result);
            return retVal.FolderNames;
        }
        
        private System.IAsyncResult OnBeginGetFolders(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetFolders(callback, asyncState);
        }
        
        private object[] OnEndGetFolders(System.IAsyncResult result) {
            string[] retVal = this.EndGetFolders(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFoldersCompleted(object state) {
            if ((this.GetFoldersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFoldersCompleted(this, new GetFoldersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFoldersAsync() {
            this.GetFoldersAsync(null);
        }
        
        public void GetFoldersAsync(object userState) {
            if ((this.onBeginGetFoldersDelegate == null)) {
                this.onBeginGetFoldersDelegate = new BeginOperationDelegate(this.OnBeginGetFolders);
            }
            if ((this.onEndGetFoldersDelegate == null)) {
                this.onEndGetFoldersDelegate = new EndOperationDelegate(this.OnEndGetFolders);
            }
            if ((this.onGetFoldersCompletedDelegate == null)) {
                this.onGetFoldersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFoldersCompleted);
            }
            base.InvokeAsync(this.onBeginGetFoldersDelegate, null, this.onEndGetFoldersDelegate, this.onGetFoldersCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ListaSerwisow.ArcGIS.ServiceCatalogPort.BeginGetServiceDescriptions(ListaSerwisow.ArcGIS.GetServiceDescriptionsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetServiceDescriptions(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetServiceDescriptions(System.AsyncCallback callback, object asyncState) {
            ListaSerwisow.ArcGIS.GetServiceDescriptionsRequest inValue = new ListaSerwisow.ArcGIS.GetServiceDescriptionsRequest();
            return ((ListaSerwisow.ArcGIS.ServiceCatalogPort)(this)).BeginGetServiceDescriptions(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ListaSerwisow.ArcGIS.GetServiceDescriptionsResponse ListaSerwisow.ArcGIS.ServiceCatalogPort.EndGetServiceDescriptions(System.IAsyncResult result) {
            return base.Channel.EndGetServiceDescriptions(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private ListaSerwisow.ArcGIS.ServiceDescription[] EndGetServiceDescriptions(System.IAsyncResult result) {
            ListaSerwisow.ArcGIS.GetServiceDescriptionsResponse retVal = ((ListaSerwisow.ArcGIS.ServiceCatalogPort)(this)).EndGetServiceDescriptions(result);
            return retVal.ServiceDescriptions;
        }
        
        private System.IAsyncResult OnBeginGetServiceDescriptions(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetServiceDescriptions(callback, asyncState);
        }
        
        private object[] OnEndGetServiceDescriptions(System.IAsyncResult result) {
            ListaSerwisow.ArcGIS.ServiceDescription[] retVal = this.EndGetServiceDescriptions(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetServiceDescriptionsCompleted(object state) {
            if ((this.GetServiceDescriptionsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetServiceDescriptionsCompleted(this, new GetServiceDescriptionsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetServiceDescriptionsAsync() {
            this.GetServiceDescriptionsAsync(null);
        }
        
        public void GetServiceDescriptionsAsync(object userState) {
            if ((this.onBeginGetServiceDescriptionsDelegate == null)) {
                this.onBeginGetServiceDescriptionsDelegate = new BeginOperationDelegate(this.OnBeginGetServiceDescriptions);
            }
            if ((this.onEndGetServiceDescriptionsDelegate == null)) {
                this.onEndGetServiceDescriptionsDelegate = new EndOperationDelegate(this.OnEndGetServiceDescriptions);
            }
            if ((this.onGetServiceDescriptionsCompletedDelegate == null)) {
                this.onGetServiceDescriptionsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetServiceDescriptionsCompleted);
            }
            base.InvokeAsync(this.onBeginGetServiceDescriptionsDelegate, null, this.onEndGetServiceDescriptionsDelegate, this.onGetServiceDescriptionsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ListaSerwisow.ArcGIS.ServiceCatalogPort.BeginRequiresTokens(ListaSerwisow.ArcGIS.RequiresTokensRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRequiresTokens(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginRequiresTokens(System.AsyncCallback callback, object asyncState) {
            ListaSerwisow.ArcGIS.RequiresTokensRequest inValue = new ListaSerwisow.ArcGIS.RequiresTokensRequest();
            return ((ListaSerwisow.ArcGIS.ServiceCatalogPort)(this)).BeginRequiresTokens(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ListaSerwisow.ArcGIS.RequiresTokensResponse ListaSerwisow.ArcGIS.ServiceCatalogPort.EndRequiresTokens(System.IAsyncResult result) {
            return base.Channel.EndRequiresTokens(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndRequiresTokens(System.IAsyncResult result) {
            ListaSerwisow.ArcGIS.RequiresTokensResponse retVal = ((ListaSerwisow.ArcGIS.ServiceCatalogPort)(this)).EndRequiresTokens(result);
            return retVal.Result;
        }
        
        private System.IAsyncResult OnBeginRequiresTokens(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginRequiresTokens(callback, asyncState);
        }
        
        private object[] OnEndRequiresTokens(System.IAsyncResult result) {
            bool retVal = this.EndRequiresTokens(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRequiresTokensCompleted(object state) {
            if ((this.RequiresTokensCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RequiresTokensCompleted(this, new RequiresTokensCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RequiresTokensAsync() {
            this.RequiresTokensAsync(null);
        }
        
        public void RequiresTokensAsync(object userState) {
            if ((this.onBeginRequiresTokensDelegate == null)) {
                this.onBeginRequiresTokensDelegate = new BeginOperationDelegate(this.OnBeginRequiresTokens);
            }
            if ((this.onEndRequiresTokensDelegate == null)) {
                this.onEndRequiresTokensDelegate = new EndOperationDelegate(this.OnEndRequiresTokens);
            }
            if ((this.onRequiresTokensCompletedDelegate == null)) {
                this.onRequiresTokensCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRequiresTokensCompleted);
            }
            base.InvokeAsync(this.onBeginRequiresTokensDelegate, null, this.onEndRequiresTokensDelegate, this.onRequiresTokensCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ListaSerwisow.ArcGIS.ServiceCatalogPort.BeginGetServiceDescriptionsEx(ListaSerwisow.ArcGIS.GetServiceDescriptionsExRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetServiceDescriptionsEx(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetServiceDescriptionsEx(string FolderName, System.AsyncCallback callback, object asyncState) {
            ListaSerwisow.ArcGIS.GetServiceDescriptionsExRequest inValue = new ListaSerwisow.ArcGIS.GetServiceDescriptionsExRequest();
            inValue.FolderName = FolderName;
            return ((ListaSerwisow.ArcGIS.ServiceCatalogPort)(this)).BeginGetServiceDescriptionsEx(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ListaSerwisow.ArcGIS.GetServiceDescriptionsExResponse ListaSerwisow.ArcGIS.ServiceCatalogPort.EndGetServiceDescriptionsEx(System.IAsyncResult result) {
            return base.Channel.EndGetServiceDescriptionsEx(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private ListaSerwisow.ArcGIS.ServiceDescription[] EndGetServiceDescriptionsEx(System.IAsyncResult result) {
            ListaSerwisow.ArcGIS.GetServiceDescriptionsExResponse retVal = ((ListaSerwisow.ArcGIS.ServiceCatalogPort)(this)).EndGetServiceDescriptionsEx(result);
            return retVal.ServiceDescriptions;
        }
        
        private System.IAsyncResult OnBeginGetServiceDescriptionsEx(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string FolderName = ((string)(inValues[0]));
            return this.BeginGetServiceDescriptionsEx(FolderName, callback, asyncState);
        }
        
        private object[] OnEndGetServiceDescriptionsEx(System.IAsyncResult result) {
            ListaSerwisow.ArcGIS.ServiceDescription[] retVal = this.EndGetServiceDescriptionsEx(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetServiceDescriptionsExCompleted(object state) {
            if ((this.GetServiceDescriptionsExCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetServiceDescriptionsExCompleted(this, new GetServiceDescriptionsExCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetServiceDescriptionsExAsync(string FolderName) {
            this.GetServiceDescriptionsExAsync(FolderName, null);
        }
        
        public void GetServiceDescriptionsExAsync(string FolderName, object userState) {
            if ((this.onBeginGetServiceDescriptionsExDelegate == null)) {
                this.onBeginGetServiceDescriptionsExDelegate = new BeginOperationDelegate(this.OnBeginGetServiceDescriptionsEx);
            }
            if ((this.onEndGetServiceDescriptionsExDelegate == null)) {
                this.onEndGetServiceDescriptionsExDelegate = new EndOperationDelegate(this.OnEndGetServiceDescriptionsEx);
            }
            if ((this.onGetServiceDescriptionsExCompletedDelegate == null)) {
                this.onGetServiceDescriptionsExCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetServiceDescriptionsExCompleted);
            }
            base.InvokeAsync(this.onBeginGetServiceDescriptionsExDelegate, new object[] {
                        FolderName}, this.onEndGetServiceDescriptionsExDelegate, this.onGetServiceDescriptionsExCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ListaSerwisow.ArcGIS.ServiceCatalogPort CreateChannel() {
            return new ServiceCatalogPortClientChannel(this);
        }
        
        private class ServiceCatalogPortClientChannel : ChannelBase<ListaSerwisow.ArcGIS.ServiceCatalogPort>, ListaSerwisow.ArcGIS.ServiceCatalogPort {
            
            public ServiceCatalogPortClientChannel(System.ServiceModel.ClientBase<ListaSerwisow.ArcGIS.ServiceCatalogPort> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetMessageVersion(ListaSerwisow.ArcGIS.GetMessageVersionRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetMessageVersion", _args, callback, asyncState);
                return _result;
            }
            
            public ListaSerwisow.ArcGIS.GetMessageVersionResponse EndGetMessageVersion(System.IAsyncResult result) {
                object[] _args = new object[0];
                ListaSerwisow.ArcGIS.GetMessageVersionResponse _result = ((ListaSerwisow.ArcGIS.GetMessageVersionResponse)(base.EndInvoke("GetMessageVersion", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetMessageFormats(ListaSerwisow.ArcGIS.GetMessageFormatsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetMessageFormats", _args, callback, asyncState);
                return _result;
            }
            
            public ListaSerwisow.ArcGIS.GetMessageFormatsResponse EndGetMessageFormats(System.IAsyncResult result) {
                object[] _args = new object[0];
                ListaSerwisow.ArcGIS.GetMessageFormatsResponse _result = ((ListaSerwisow.ArcGIS.GetMessageFormatsResponse)(base.EndInvoke("GetMessageFormats", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTokenServiceURL(ListaSerwisow.ArcGIS.GetTokenServiceURLRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetTokenServiceURL", _args, callback, asyncState);
                return _result;
            }
            
            public ListaSerwisow.ArcGIS.GetTokenServiceURLResponse EndGetTokenServiceURL(System.IAsyncResult result) {
                object[] _args = new object[0];
                ListaSerwisow.ArcGIS.GetTokenServiceURLResponse _result = ((ListaSerwisow.ArcGIS.GetTokenServiceURLResponse)(base.EndInvoke("GetTokenServiceURL", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetFolders(ListaSerwisow.ArcGIS.GetFoldersRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetFolders", _args, callback, asyncState);
                return _result;
            }
            
            public ListaSerwisow.ArcGIS.GetFoldersResponse EndGetFolders(System.IAsyncResult result) {
                object[] _args = new object[0];
                ListaSerwisow.ArcGIS.GetFoldersResponse _result = ((ListaSerwisow.ArcGIS.GetFoldersResponse)(base.EndInvoke("GetFolders", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetServiceDescriptions(ListaSerwisow.ArcGIS.GetServiceDescriptionsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetServiceDescriptions", _args, callback, asyncState);
                return _result;
            }
            
            public ListaSerwisow.ArcGIS.GetServiceDescriptionsResponse EndGetServiceDescriptions(System.IAsyncResult result) {
                object[] _args = new object[0];
                ListaSerwisow.ArcGIS.GetServiceDescriptionsResponse _result = ((ListaSerwisow.ArcGIS.GetServiceDescriptionsResponse)(base.EndInvoke("GetServiceDescriptions", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRequiresTokens(ListaSerwisow.ArcGIS.RequiresTokensRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("RequiresTokens", _args, callback, asyncState);
                return _result;
            }
            
            public ListaSerwisow.ArcGIS.RequiresTokensResponse EndRequiresTokens(System.IAsyncResult result) {
                object[] _args = new object[0];
                ListaSerwisow.ArcGIS.RequiresTokensResponse _result = ((ListaSerwisow.ArcGIS.RequiresTokensResponse)(base.EndInvoke("RequiresTokens", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetServiceDescriptionsEx(ListaSerwisow.ArcGIS.GetServiceDescriptionsExRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetServiceDescriptionsEx", _args, callback, asyncState);
                return _result;
            }
            
            public ListaSerwisow.ArcGIS.GetServiceDescriptionsExResponse EndGetServiceDescriptionsEx(System.IAsyncResult result) {
                object[] _args = new object[0];
                ListaSerwisow.ArcGIS.GetServiceDescriptionsExResponse _result = ((ListaSerwisow.ArcGIS.GetServiceDescriptionsExResponse)(base.EndInvoke("GetServiceDescriptionsEx", _args, result)));
                return _result;
            }
        }
    }
}
